language:
  - python
python:
  - 3.5
install:
  - pip install --upgrade pytest
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install biopython
script:
  tests/run_tests.sh
notifications:
  email:
    on_success: never
    on_failure: never
after_success:
  coveralls
