language:
  - python
python:
  - 3.5
install:
  - pip install pytest
script:
  - py.test -vv bioinfo.py
  - py.test -vv sort_by_blast.py
  - py.test -vv filter.py
notifications:
  email:
    on_success: never
    on_failure: never