language:
  - python
python:
  - 3.5
install:
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install biopython
script:
  py.test -vv bioinfo.py conservation.py filter.py sort_by_blast.py --cov=bioinfo --cov=conservation --cov=filter --cov=sort_by_blast
notifications:
  email:
    on_success: never
    on_failure: never
after_success:
  coveralls
