language:
  - python
python:
  - 3.5
install:
  - pip install pytest-cov
  - pip install python-coveralls
script:
  - py.test -vv bioinfo.py --cov bioinfo
  - py.test -vv sort_by_blast.py --cov sort_by_blast
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: never